### ISSUE TITLE
型名の途中にドットが含まれていると、名前空間として変換されてしまう不具合

### ISSUE THREAD

**Issue by y-matsuda** [ChangeVision/astah-csharp-reverse-plugin#5]
### 概要

パッケージ名とクラス名が不正になる
![image](https://cloud.githubusercontent.com/assets/1912519/6184818/ef039c46-b3a9-11e4-9f2c-bdd5b4522453.png)

型名の途中にドットが含まれているために名前空間として変換されてしまった。
nunit-3.0.0-alpha-5/src/NUnitEngine/mono-addins/Mono.Addins/ExtensionNode.cs

``` c#
void ReadObject (object ob, NodeAttribute[] attributes, Dictionary<string,ExtensionNodeType.FieldData> fields) { }
```
### 関連issue
- #1

**Comment by m-daida** [comment]
#### 不具合1
- "ExtensionNodeType.FieldData"という名前のクラスができる
- ![sshot 2015-02-20 at 11 46 23](https://cloud.githubusercontent.com/assets/4626544/6280873/3943df98-b8f8-11e4-9ced-aa08fc743117.png)
- ExtentionNodeTypeのインナークラスFieldDataは正しく作成されているので、上記クラスは不要
![sshot 2015-02-20 at 12 05 51](https://cloud.githubusercontent.com/assets/4626544/6280904/dbb76d76-b8f8-11e4-8719-e47260cd5ee1.png)

#### 不具合2
- ExtensionNodeTypeクラスとExtensionNodeTypeパッケージができる
 - パッケージは不要?
- ![sshot 2015-02-20 at 11 46 55](https://cloud.githubusercontent.com/assets/4626544/6280876/43fa1ff6-b8f8-11e4-830d-fb252e5ec1f3.png)
- ![sshot 2015-02-20 at 11 47 12](https://cloud.githubusercontent.com/assets/4626544/6280877/46a1a6a2-b8f8-11e4-8fef-52ffb15efcad.png)

#### 不具合3
- `Dictionary<string,ExtensionNodeType.FieldData>`は無名クラスだが、関係するモデルを図に追加してもテンプレートバインディングが表示されない
- ![sshot 2015-02-20 at 12 03 10](https://cloud.githubusercontent.com/assets/4626544/6280888/8255ef3c-b8f8-11e4-909e-c5e094236873.png)
